// styles/blueprintStyles.js
// All shared inline style objects used across BlueprintDesign components.
// Import as: import S from '../styles/blueprintStyles';
// (or import { blueprintStyles as S } for named import)

const blueprintStyles = {
  toolBtn: {
    padding: "5px 12px",
    background: "#2d4a6e",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 500,
    whiteSpace: "nowrap",
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  propInput: {
    width: "100%",
    padding: "4px 7px",
    border: "1px solid #334155",
    borderRadius: 4,
    fontSize: 11,
    background: "#0f172a",
    color: "#e2e8f0",
    boxSizing: "border-box",
  },
  panelLabel: {
    fontSize: 10,
    fontWeight: 700,
    color: "#475569",
    textTransform: "uppercase",
    letterSpacing: 1,
    margin: "0 0 8px",
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  propLabel: {
    fontSize: 10,
    color: "#64748b",
    display: "block",
    marginBottom: 3,
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  floatingPanelLeft: {
    position: "absolute",
    top: 58,
    left: 18,
    width: 336,
    maxHeight: "calc(100% - 76px)",
    overflow: "hidden",
    background:
      "linear-gradient(180deg, rgba(5,10,22,.97) 0%, rgba(8,15,30,.95) 100%)",
    border: "1px solid rgba(96,165,250,.14)",
    borderRadius: 16,
    padding: 14,
    backdropFilter: "blur(10px)",
    boxShadow: "0 18px 40px rgba(0,0,0,.34)",
    boxSizing: "border-box",
  },
  floatingPanelRight: {
    position: "absolute",
    top: 14,
    right: 14,
    width: 260,
    maxHeight: "calc(100% - 30px)",
    overflowY: "auto",
    background: "rgba(9,14,25,.82)",
    border: "1px solid rgba(148,163,184,.14)",
    borderRadius: 12,
    padding: 12,
    backdropFilter: "blur(8px)",
    boxShadow: "0 10px 30px rgba(0,0,0,.25)",
  },

  inspectorDockedPanel: {
    position: "absolute",
    top: 14,
    right: 14,
    width: 340,
    maxHeight: "calc(100% - 28px)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: "rgba(9,14,25,.88)",
    border: "1px solid rgba(148,163,184,.14)",
    borderRadius: 14,
    padding: 12,
    backdropFilter: "blur(8px)",
    boxShadow: "0 10px 30px rgba(0,0,0,.25)",
    zIndex: 9,
  },

  inspectorTabsRow: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 8,
    marginBottom: 10,
  },

  inspectorTabBtn: {
    height: 36,
    padding: "0 10px",
    borderRadius: 10,
    border: "1px solid rgba(71,85,105,.72)",
    background: "rgba(11,20,36,.92)",
    color: "#b7c5da",
    cursor: "pointer",
    fontSize: 11,
    fontWeight: 700,
  },

  inspectorTabBtnActive: {
    border: "1px solid rgba(96,165,250,.65)",
    background:
      "linear-gradient(180deg, rgba(37,99,235,.28) 0%, rgba(29,78,216,.2) 100%)",
    color: "#eef4ff",
    boxShadow: "inset 0 0 0 1px rgba(147,197,253,.08)",
  },

  inspectorTabBody: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    paddingRight: 2,
  },

  smartActionsPanelDocked: {
    position: "relative",
    inset: "auto",
    width: "100%",
    maxHeight: "none",
    overflowY: "visible",
    padding: 0,
    borderRadius: 0,
    background: "transparent",
    border: "none",
    boxShadow: "none",
    backdropFilter: "none",
    zIndex: "auto",
  },

  floatingTitle: {
    fontSize: 12,
    fontWeight: 800,
    color: "#e5efff",
    textTransform: "uppercase",
    letterSpacing: 1.2,
    marginBottom: 0,
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  floatingSectionLabel: {
    fontSize: 10,
    fontWeight: 700,
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 1,
    margin: "8px 0 8px",
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  floatingPaletteBtn: {
    width: "100%",
    minHeight: 38,
    textAlign: "left",
    padding: "9px 10px",
    border: "1px solid rgba(55,78,112,.55)",
    background:
      "linear-gradient(180deg, rgba(10,19,36,.98) 0%, rgba(8,15,29,.98) 100%)",
    borderRadius: 10,
    cursor: "pointer",
    fontSize: 11,
    color: "#dbe7ff",
    display: "flex",
    alignItems: "center",
    gap: 8,
    boxShadow: "inset 0 1px 0 rgba(255,255,255,.03)",
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  floatingPrimaryBtn: {
    width: "100%",
    minHeight: 40,
    textAlign: "left",
    padding: "9px 10px",
    border: "1px solid rgba(96,165,250,.55)",
    background: "linear-gradient(180deg, #2f6df6 0%, #1d4ed8 100%)",
    borderRadius: 10,
    cursor: "pointer",
    fontSize: 11,
    color: "#ffffff",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    gap: 8,
    boxShadow:
      "0 8px 18px rgba(37,99,235,.28), inset 0 1px 0 rgba(255,255,255,.14)",
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  activeBuildPill: {
    background: "rgba(20,184,166,.14)",
    border: "1px solid rgba(20,184,166,.45)",
    color: "#99f6e4",
    borderRadius: 999,
    padding: "6px 10px",
    fontSize: 10,
    marginBottom: 10,
    lineHeight: 1.4,
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  floatingLabel: {
    display: "block",
    fontSize: 10,
    color: "#94a3b8",
    marginBottom: 3,
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  floatingInput: {
    width: "100%",
    padding: "5px 7px",
    border: "1px solid #334155",
    borderRadius: 4,
    fontSize: 11,
    background: "#0f172a",
    color: "#e2e8f0",
    boxSizing: "border-box",
  },
  infoCard: {
    padding: 10,
    borderRadius: 8,
    background: "#0f172a",
    border: "1px solid #334155",
    color: "#cbd5e1",
    fontSize: 11,
    lineHeight: 1.8,
    marginBottom: 10,
  },
  unityToolbar: {
    position: "absolute",
    top: 74,
    left: 18,
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: 6,
    borderRadius: 12,
    background: "rgba(18,27,44,.9)",
    border: "1px solid rgba(148,163,184,.16)",
    boxShadow: "0 10px 22px rgba(0,0,0,.28)",
    backdropFilter: "blur(8px)",
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  unityToolBtn: {
    width: 34,
    height: 34,
    border: "1px solid #475569",
    background: "linear-gradient(180deg, #334155 0%, #1f2937 100%)",
    color: "#e5e7eb",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: 18,
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  unityToolBtnActive: {
    background: "linear-gradient(180deg, #60a5fa 0%, #2563eb 100%)",
    border: "1px solid #93c5fd",
    color: "#ffffff",
    boxShadow: "0 0 0 1px rgba(147,197,253,.2) inset",
  },

  smartActionsPanel: {
    position: "absolute",
    bottom: 14,
    left: 14,
    width: 320,
    maxHeight: "calc(100% - 28px)",
    overflowY: "auto",
    padding: 12,
    borderRadius: 14,
    background: "rgba(9,14,25,.86)",
    border: "1px solid rgba(148,163,184,.16)",
    boxShadow: "0 10px 30px rgba(0,0,0,.28)",
    backdropFilter: "blur(8px)",
    zIndex: 8,
    userSelect: "none",
    WebkitUserSelect: "none",
  },

  smartActionsTitle: {
    fontSize: 11,
    fontWeight: 800,
    color: "#e5efff",
    textTransform: "uppercase",
    letterSpacing: 1.1,
    marginBottom: 4,
  },
  smartActionsSubtle: {
    fontSize: 10,
    color: "#94a3b8",
    lineHeight: 1.4,
    marginBottom: 10,
  },
  smartActionsSectionLabel: {
    fontSize: 10,
    fontWeight: 700,
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 1,
    margin: "10px 0 6px",
  },
  smartActionsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 6,
  },

  smartActionsWideGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 6,
  },
  smartActionsFieldsRow: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 6,
    marginBottom: 8,
  },
  smartActionsField: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  smartActionsInput: {
    width: "100%",
    height: 32,
    padding: "0 8px",
    borderRadius: 8,
    border: "1px solid rgba(71,85,105,.72)",
    background: "rgba(8,17,32,.96)",
    color: "#e2e8f0",
    fontSize: 11,
    boxSizing: "border-box",
  },

  smartActionBtn: {
    minHeight: 32,
    padding: "0 8px",
    borderRadius: 8,
    border: "1px solid rgba(71,85,105,.72)",
    background:
      "linear-gradient(180deg, rgba(30,41,59,.96) 0%, rgba(15,23,42,.96) 100%)",
    color: "#e2e8f0",
    fontSize: 10,
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  smartActionBtnWarn: {
    minHeight: 32,
    padding: "0 8px",
    borderRadius: 8,
    border: "1px solid rgba(245,158,11,.45)",
    background:
      "linear-gradient(180deg, rgba(120,53,15,.96) 0%, rgba(69,26,3,.96) 100%)",
    color: "#fde68a",
    fontSize: 10,
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  smallPill: {
    fontSize: 11,
    background: "rgba(20,184,166,.14)",
    padding: "2px 10px",
    borderRadius: 20,
    color: "#99f6e4",
    border: "1px solid rgba(20,184,166,.35)",
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  fullScreenWrapper: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    zIndex: 9999,
    display: "flex",
    flexDirection: "column",
    background: "#0f172a",
    overflow: "hidden",
  },
  floatingDrawerPanel: {
    width: 336,
    maxHeight: "calc(100% - 76px)",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    gap: 12,
    boxSizing: "border-box",
    zIndex: 5,
    transition: "opacity .18s ease, transform .18s ease",
  },

  libraryToggleBtn: {
    position: "absolute",
    top: 16,
    left: 18,
    height: 40,
    padding: "0 14px",
    borderRadius: 12,
    border: "1px solid rgba(96,165,250,.2)",
    background: "rgba(20,29,46,.95)",
    color: "#eef4ff",
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    cursor: "pointer",
    boxShadow: "0 10px 24px rgba(0,0,0,.26)",
    backdropFilter: "blur(8px)",
    fontSize: 12,
    fontWeight: 700,
    zIndex: 6,
    userSelect: "none",
    WebkitUserSelect: "none",
  },

  libraryToggleBtnActive: {
    background: "linear-gradient(180deg, #2563eb 0%, #1d4ed8 100%)",
    border: "1px solid rgba(147,197,253,.55)",
    color: "#ffffff",
  },

  libraryHeaderRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },

  librarySubtleText: {
    fontSize: 10,
    color: "#94a3b8",
    lineHeight: 1.45,
    marginTop: 2,
    marginBottom: 0,
  },

  libraryStickyTop: {
    paddingBottom: 10,
    marginBottom: 10,
    borderBottom: "1px solid rgba(51,65,85,.72)",
  },

  librarySummaryRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 5,
    marginTop: 8,
  },

  librarySummaryPill: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 20,
    padding: "0 7px",
    borderRadius: 999,
    border: "1px solid rgba(71,85,105,.62)",
    background: "rgba(11,20,36,.88)",
    color: "#c7d3e6",
    fontSize: 9,
    fontWeight: 700,
    lineHeight: 1,
    letterSpacing: ".02em",
    whiteSpace: "nowrap",
    userSelect: "none",
    WebkitUserSelect: "none",
  },

  librarySectionCard: {
    border: "1px solid rgba(51,65,85,.76)",
    background:
      "linear-gradient(180deg, rgba(7,14,26,.96) 0%, rgba(5,11,21,.96) 100%)",
    borderRadius: 12,
    padding: 6,
    boxSizing: "border-box",
  },

  librarySectionToggle: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    background: "transparent",
    border: "none",
    padding: 0,
    cursor: "pointer",
    textAlign: "left",
  },

  librarySectionToggleTitle: {
    fontSize: 10,
    fontWeight: 800,
    color: "#94a3b8",
    textTransform: "uppercase",
    letterSpacing: 1.1,
    lineHeight: 1.3,
  },

  librarySectionToggleMeta: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    flexShrink: 0,
  },

  librarySectionCount: {
    minWidth: 18,
    height: 18,
    padding: "0 7px",
    borderRadius: 999,
    border: "1px solid rgba(71,85,105,.62)",
    background: "rgba(15,23,42,.92)",
    color: "#d7e3f7",
    fontSize: 9,
    fontWeight: 700,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    boxSizing: "border-box",
  },

  libraryChevron: {
    width: 18,
    height: 18,
    borderRadius: 999,
    border: "1px solid rgba(71,85,105,.62)",
    background: "rgba(15,23,42,.92)",
    color: "#c7d2fe",
    fontSize: 10,
    fontWeight: 800,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    boxSizing: "border-box",
  },

  librarySectionItems: {
    display: "grid",
    gap: 6,
    marginTop: 8,
  },

  libraryItemPrimaryText: {
    display: "block",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: 10,
    fontWeight: 700,
    lineHeight: 1.35,
    textAlign: "left",
  },

  libraryItemSecondaryText: {
    display: "block",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: 9,
    fontWeight: 500,
    lineHeight: 1.35,
    textAlign: "left",
  },

  libraryCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 10,
    border: "1px solid rgba(148,163,184,.14)",
    background: "rgba(15,23,42,.9)",
    color: "#d7e3f7",
    cursor: "pointer",
    fontSize: 18,
    lineHeight: 1,
    flexShrink: 0,
  },

  floatingSearchInput: {
    width: "100%",
    height: 34,
    padding: "0 10px",
    border: "1px solid rgba(71,85,105,.72)",
    borderRadius: 10,
    fontSize: 12,
    background: "rgba(8,17,32,.96)",
    color: "#e2e8f0",
    boxSizing: "border-box",
    outline: "none",
  },

  libraryTabsRow: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: 8,
    marginBottom: 4,
  },

  libraryTabBtn: {
    height: 32,
    padding: "0 8px",
    borderRadius: 9,
    border: "1px solid rgba(71,85,105,.72)",
    background: "rgba(11,20,36,.9)",
    color: "#b7c5da",
    cursor: "pointer",
    fontSize: 10,
    fontWeight: 700,
  },

  libraryTabBtnActive: {
    border: "1px solid rgba(96,165,250,.65)",
    background:
      "linear-gradient(180deg, rgba(37,99,235,.28) 0%, rgba(29,78,216,.2) 100%)",
    color: "#eef4ff",
    boxShadow: "inset 0 0 0 1px rgba(147,197,253,.08)",
  },

  libraryGroupsWrap: {
    display: "grid",
    gap: 8,
    overflowY: "auto",
    paddingRight: 4,
    marginRight: -4,
    alignContent: "start",
  },

  libraryEmptyState: {
    padding: "18px 12px",
    borderRadius: 12,
    border: "1px dashed rgba(148,163,184,.22)",
    color: "#9eb0c7",
    textAlign: "center",
    fontSize: 11,
    background: "rgba(10,18,32,.62)",
  },
};

export default blueprintStyles;
export { blueprintStyles as S };
